name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
  

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Where i am
      run: |
        ls
        pwd

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Where i am
      run: |
        ls
        pwd